[[plugins]]
repo = 'Shougo/dein.vim'

# colorscheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'romainl/Apprentice'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  nnoremap <silent><Space>r :cclose<CR>:QuickRun<CR>
  au FileType qf nnoremap <silent><buffer>q :quit<CR>
  let g:quickrun_config = {
    \'_' : {
    \  'runner' : 'vimproc',
    \  'runner/vimproc/updatetime' : 40,
    \  'hook/close_buffer/enable_failure' : 1,
    \  'hook/close_quickfix/enable_success' : 1,
    \  'outputter/buffer/split' : ':botright 8sp',
    \  'outputter/error/success' : 'buffer',
    \  'outputter/error/error' : 'quickfix',
    \  'outputter/buffer/into' : '1',
    \  'outputter/quickfix/errorformat': '%f:%l, %m in %f on line %l',
    \  'outputter/buffer/close_on_empty': 1,
    \  'outputter' : 'error',
    \},
    \'tex' : {
    \  'command' : 'latexmk',
    \  'cmdopt' : '-pv',
    \  'exec' : ['%c %o %s']
    \},
    \'cpp' : {
    \ 'command' : 'g++',
    \ 'cmdopt' : '-std=c++11',
    \},
    \}
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_color_term = 93
let g:indentLine_char = '¦'
let g:indentLine_leadingSpaceChar = '.'
let g:indentLine_leadingSpaceEnabled = 1
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-session'
hook_add = '''
let g:session_autosave = 'no'
let g:session_autoload = 'no'
nnoremap <Leader>ss :SaveSession
'''

#----------
# syntax
#----------

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
